services:
  d-dev-react:
    image: node:22-slim
    container_name: d-dev-react
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: bash
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "${REACT_PORT:-3000}:3000"
    networks:
      - dev-net

  d-backend:
    build: ./backend
    container_name: d-backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    depends_on:
      - d-db
    networks:
      - dev-net

  d-db:
    image: postgres:17
    container_name: d-postgres17
    restart: always

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - dev-net

volumes:
  postgres_data:

networks:
  dev-net:
    external: true
